Взаимодействие с пользователем с помощь RestApi
bledbereq/UserServiceAuth pull request #10
Opened 2024-07-02 05:05 UTC by bledbereq

Close #9

2024-07-02 05:34 UTC, f0rwhat requested changes
Дочистить ветку, подойти для обсуждения архитектуры

2024-07-02 05:34 UTC, f0rwhat commented on .gitignore
> +do.sum
Они не должны быть в .gitignore

2024-07-02 05:34 UTC, f0rwhat commented on Taskfile.yaml
> +      - protoc -I proto proto/publickey.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
Добавить в readme описание как этим пользоваться

2024-07-02 05:34 UTC, f0rwhat commented on cmd/main.go
> +	application.GRPCSrv.Stop()
А остановить http сервер?

2024-07-02 05:34 UTC, f0rwhat commented on cmd/main.go
> +	log.Warn("warn message")
Добавлял, чтобы проверить логгер? Убрать, т.к. не нужно в итоговом коде

2024-07-02 05:34 UTC, f0rwhat commented on cmd/funct.go
> +}
Сделать из этого отдельную сущность-обработчик. Оставлять их свободными не получится, т.к. в дальнейшем тебе нужно будет сохранять записи в БД и обновлять там ключи. Откуда доступ к БД возьмется тут?

2024-07-02 05:34 UTC, f0rwhat commented on cmd/main.go
> +)
Что означает env local?

2024-07-02 05:34 UTC, f0rwhat commented on .gitignore
> +do.sum
А вот всё, что генерируется из протобофа - наоборот добавить

2024-07-02 05:34 UTC, f0rwhat commented on internal/app/grpc/app.go
> +package grpcapp
Дочистить репозиторий - в этом мерже не должно быть ничего связанного с grpc

2024-07-02 05:34 UTC, f0rwhat commented on cmd/funct.go
> +}
+, почему это в cmd, а не в internal, как ты сделал это с grpc?

2024-07-02 05:34 UTC, f0rwhat commented on internal/config/config.go
> +type GRPSconfig struct {
GRPSconfig -> GrpcConfig

2024-07-02 05:34 UTC, f0rwhat commented on internal/config/config.go
> +	flag.Parse()
Лучше парсить все аргументы CLI в main.go и передавать их дальше в качестве аргументов

2024-07-02 05:34 UTC, f0rwhat commented on lib/functions/functions.go
> +package functions
Какое предназначение у папки lib?
Если тут ты используешь код, взятый из чужих репозиториев - файлы должны быть не скопированы, а добавлены субмодулем.
Если это твой код - ему не место в lib.
Если это какие-то твои утиллиты, то их следует переместить в internal/utils

2024-07-03 03:49 UTC, f0rwhat commented on internal/router/auth.go
> +		return echo.NewHTTPError(http.StatusBadRequest, err.Error())
Будет хорошо, если здесь будет описана ошибка.

2024-07-03 03:49 UTC, f0rwhat commented on Taskfile.yaml
> +      - protoc -I proto proto/publickey.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
Можно резолвить

2024-07-03 03:49 UTC, f0rwhat commented on cmd/main.go
> +	application.GRPCSrv.Stop()
Можно резолвить

2024-07-03 03:50 UTC, f0rwhat commented on cmd/main.go
> +	log.Warn("warn message")
Можно резолвить

2024-07-03 03:50 UTC, f0rwhat commented on cmd/funct.go
> +}
Можно резолвить

2024-07-03 03:50 UTC, f0rwhat commented on cmd/main.go
> +)
Можно резолвить

2024-07-03 03:50 UTC, f0rwhat commented on internal/app/grpc/app.go
> +package grpcapp
Можно резолвить

2024-07-03 03:50 UTC, f0rwhat commented on internal/config/config.go
> +type GRPSconfig struct {
Можно резолвить

2024-07-03 03:51 UTC, f0rwhat commented
Куда подевались тесты?

2024-07-03 03:51 UTC, f0rwhat commented on lib/functions/functions.go
> +package functions
Можно резолвить

2024-07-03 03:51 UTC, f0rwhat commented on internal/config/config.go
> +	flag.Parse()
Можно резолвить

2024-07-03 03:56 UTC, Diklofozzz1 commented on cmd/main.go
> +	}()
Посмотри что такое syncGroup и вообще библиотечка sync. Да, тут одна горутина. но если их будет много, она станет твоим незаменимым другом. ибо если умрёт область видимости, то умрет и горутина. Тебя будут интересовать методы WaitGroup.Add(), WaitGroup.Wait() и WaitGroup.Done().

2024-07-03 04:02 UTC, Diklofozzz1 commented on cmd/main.go
> +	}()
это рекомендация, можешь резолвнуть... но для мульти горутин настоятельно рекомендую понять, как ее юзать

2024-07-03 05:40 UTC, f0rwhat requested changes

2024-07-03 05:40 UTC, f0rwhat commented on internal/router/auth.go
> +		return echo.NewHTTPError(http.StatusBadRequest, err.Error())
Я имел ввиду не комментарий, а сообщение в err.Error()

2024-07-03 06:58 UTC, merged