Инициализация БД и подключение к ней через GORM
bledbereq/UserServiceAuth pull request #16
Opened 2024-07-04 08:48 UTC by bledbereq

Close #15

2024-07-08 04:03 UTC, f0rwhat commented on internal/router/auth/auth.go
> +	}
Модель переименовать в dto и добавить json описания для сериализации/десереализации туда

2024-07-08 04:03 UTC, f0rwhat commented on internal/router/auth/auth.go
> +	}
Аналогично предыдущему треду

2024-07-08 04:05 UTC, f0rwhat commented on internal/router/auth/auth_test.go
> +}
по сути это один и тот же тест - юзкейс вернул ошибку

2024-07-08 04:07 UTC, f0rwhat commented on internal/router/auth/auth_test.go
> +}
Аналогично - тест один и тот же.

2024-07-09 03:28 UTC, f0rwhat commented on internal/router/auth/auth_test.go
> +}
Это должно быть в тесте юзкейса, а это тест роутера. Роутеру все равно какая ошибка - если есть - должен быть bad request и соотв. текст. Если нет - вернуть 200.

2024-07-10 03:12 UTC, Diklofozzz1 commented on config/local.yaml
> +  address: 0.0.0.0:8082
рекомендация: не стоит указывать подобные адреса, если работаешь в докере. Познакомься с hostname для контейнеров

2024-07-10 03:22 UTC, Diklofozzz1 commented on internal/router/auth/auth.go
> +		return ctx.JSON(http.StatusUnauthorized, map[string]string{"error": err.Error()})
на случай ошибки у echo есть специальная функция. Можно возвращать не контекст, который ты преобразуешь, а сразу ошибку, в этом случае будет выглядеть так: `return echo.NewHTTPError(http.StatusUnauthorized, map[string]string{"error": err.Error()})`.  Так ты гарантируешь запросившему клиенту, что это точно ошибка.

2024-07-10 03:24 UTC, Diklofozzz1 commented on internal/router/auth/auth.go
> +	}
ты во всех хендлерах это юзаешь... можно вынести, как middleware к запросу и избавиться от дублирования.

2024-07-11 07:12 UTC, f0rwhat requested changes

2024-07-11 07:12 UTC, f0rwhat commented on internal/router/auth/auth.go
>  }
вынести в dto

2024-07-12 02:43 UTC, merged